services:
  fuel-manager:
    build: .
    container_name: fuel-manager
    restart: always
    network_mode: bridge
    ports:
      - "8599:8599"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Europe/Rome
      - DATA_DIR=/app/data
